import mongoose from "mongoose";

const cartItemSchema = new mongoose.Schema({
    product: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product',
        required: true
    },
    quantity: {
        type: Number,
        required: true,
        default: 0
    }
}, { _id: false });// { _id: false } - This will prevent subObjects from being given autogenerated ID's. We already captured the product ID here in product and "stock" doesn't need an ID

const cartSchema = new mongoose.Schema({
    user: {//the cart user - one per user
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    items: [cartItemSchema]
})

export const cartModel = mongoose.model('Cart', cartSchema);